# Generated by Django 3.2.1 on 2021-05-10 08:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='应用')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机柜')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='phy', max_length=128, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': '设备类型',
                'verbose_name_plural': '设备类型',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(max_length=256, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='联系人')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vlaninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_net', models.CharField(max_length=128, verbose_name='网段地址')),
                ('vlan_area', models.CharField(max_length=128, verbose_name='所在区域')),
            ],
            options={
                'verbose_name': '网段信息',
                'verbose_name_plural': '网段信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip')),
                ('hostname', models.CharField(blank=True, max_length=128, verbose_name='主机名')),
                ('u', models.CharField(blank=True, max_length=32, verbose_name='U位')),
                ('oobip', models.CharField(blank=True, default='无', max_length=128, verbose_name='带外ip')),
                ('equipment_model', models.CharField(blank=True, max_length=128, verbose_name='设备型号')),
                ('mac', models.CharField(blank=True, max_length=128, verbose_name='mac地址')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='sn')),
                ('system', models.CharField(blank=True, max_length=128, verbose_name='操作系统')),
                ('kernel', models.CharField(blank=True, max_length=128, verbose_name='内核')),
                ('cpu', models.CharField(blank=True, max_length=128, verbose_name='CPU型号')),
                ('vcpu', models.CharField(blank=True, max_length=128, verbose_name='vcpus')),
                ('mem', models.CharField(blank=True, max_length=128, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=128, verbose_name='硬盘')),
                ('exceedtime', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='到期时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('app', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.appgroup', verbose_name='应用')),
                ('cabinet', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.cabinet', verbose_name='机柜')),
                ('type', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.hosttype', verbose_name='设备类型')),
                ('vlan', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='management.vlaninfo', verbose_name='网段地址')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.idc', verbose_name='所在机房'),
        ),
    ]
