# Generated by Django 3.2.1 on 2021-05-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runresult',
            old_name='iplist',
            new_name='ip',
        ),
    ]
