# Generated by Django 3.2.1 on 2021-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_rename_iplist_runresult_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='runresult',
            name='num',
            field=models.IntegerField(blank=True, default=0, verbose_name='ip数量'),
        ),
    ]
