# Generated by Django 3.2.1 on 2021-05-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_runresult_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='vlaninfo',
            name='vlan_area',
            field=models.CharField(max_length=128, verbose_name='所在环境'),
        ),
    ]
