# Generated by Django 3.2.1 on 2021-05-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210514_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Searchtype',
        ),
    ]
