# Generated by Django 3.2.1 on 2021-05-17 02:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=128, unique=True, verbose_name='应用')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'db_table': 'ops_app',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=128, unique=True, verbose_name='机柜')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
                'db_table': 'ops_cabinet',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=128, unique=True, verbose_name='机房名称')),
                ('iaddress', models.CharField(max_length=256, verbose_name='机房地址')),
                ('iphone', models.CharField(max_length=15, verbose_name='联系人')),
                ('iemail', models.EmailField(default='null', max_length=254, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
                'db_table': 'ops_idc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rctime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rip', models.TextField(blank=True, verbose_name='执行主机')),
                ('rnum', models.IntegerField(blank=True, default=0, verbose_name='ip数量')),
                ('rtype', models.CharField(blank=True, max_length=128, verbose_name='任务类型')),
                ('rargs', models.CharField(blank=True, max_length=256, verbose_name='任务参数')),
                ('ris_sudo', models.CharField(blank=True, max_length=16, verbose_name='是否root')),
                ('rstate', models.SmallIntegerField(choices=[(1, '进行中'), (2, '异常'), (3, '完成')], verbose_name='任务状态')),
                ('rustime', models.FloatField(blank=True, null=True)),
                ('rresult_txt', models.TextField(blank=True, verbose_name='命令结果')),
            ],
            options={
                'verbose_name': '执行结果',
                'verbose_name_plural': '执行结果',
                'db_table': 'ops_runresult',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnet', models.CharField(max_length=128, unique=True, verbose_name='网段地址')),
                ('varea', models.CharField(max_length=128, verbose_name='所在环境')),
            ],
            options={
                'verbose_name': '网段信息',
                'verbose_name_plural': '网段信息',
                'db_table': 'ops_vlan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hostinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('hmtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hip', models.GenericIPAddressField(unique=True, verbose_name='ip')),
                ('hhostname', models.CharField(blank=True, max_length=128, verbose_name='主机名')),
                ('htype', models.SmallIntegerField(blank=True, choices=[(1, '物理机'), (2, '宿主机'), (3, '虚拟机')], null=True, verbose_name='设备类型')),
                ('hu', models.CharField(blank=True, max_length=32, verbose_name='U位')),
                ('hoobip', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='带外ip')),
                ('hequipment_model', models.CharField(blank=True, max_length=128, verbose_name='设备型号')),
                ('hmac', models.CharField(blank=True, max_length=128, verbose_name='mac地址')),
                ('hsn', models.CharField(blank=True, max_length=128, verbose_name='sn')),
                ('hsystem', models.CharField(blank=True, max_length=128, verbose_name='操作系统')),
                ('hkernel', models.CharField(blank=True, max_length=128, verbose_name='内核')),
                ('hcpu', models.CharField(blank=True, max_length=128, verbose_name='CPU型号')),
                ('hvcpu', models.CharField(blank=True, max_length=128, verbose_name='vcpus')),
                ('hmem', models.CharField(blank=True, max_length=128, verbose_name='内存')),
                ('hdisk', models.CharField(blank=True, max_length=128, verbose_name='硬盘')),
                ('hexceedtime', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='到期时间')),
                ('hnotes', models.TextField(blank=True, verbose_name='备注')),
                ('happ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.app', verbose_name='应用')),
                ('hcabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.cabinet', verbose_name='机柜')),
                ('hidc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.idc', verbose_name='机房')),
                ('hvlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.vlan', verbose_name='网段地址')),
            ],
            options={
                'verbose_name': '服务器列表',
                'verbose_name_plural': '服务器列表',
                'db_table': 'ops_hostinfo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='cidc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ops.idc', verbose_name='所在机房'),
        ),
    ]
