# Generated by Django 3.2.1 on 2021-05-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostinfo',
            name='hproduct_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='服务器型号'),
        ),
    ]
