# Generated by Django 3.2.1 on 2021-05-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_hostinfo_hproduct_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfo',
            old_name='hequipment_model',
            new_name='hsystem_vendor',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='hbios_vendor',
            field=models.CharField(blank=True, max_length=128, verbose_name='Bios生产商'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='hproduct_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='机器型号'),
        ),
    ]
